# 引用Ubuntu
FROM ubuntu:latest
RUN mkdir -p /workspace
WORKDIR /workspace
# 添加环境
ENV TZ=Asia/Shanghai
# 安装工具
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y wget
RUN apt-get install -y git
# 安装AmiyaBot框架及运行环境
RUN git clone https://github.com/AmiyaBot/Amiya-Bot.git
RUN pip install -r /workspace/AmiyaBot/requirements.txt
# 下载运行脚本
RUN wget https://raw.githubusercontent.com/rhwong/Amiya-Bot-Docker/main/bat/start.sh
# 修复时区
RUN wget -P /usr/share/zoneinfo/Asia https://github.com/rhwong/Amiya-Bot-Docker/raw/main/timezone/Shanghai -N
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# 给予权限
RUN chmod -R 766 /workspace
# 启动
CMD /workspace/start.sh && bash